FROM heroku/heroku:20

ENV DEBIAN_FRONTEND=noninteractive
ARG DOWNLOAD_URL=https://developer.salesforce.com/media/salesforce-cli/sf/channels/nightly/sf-linux-x64.tar.xz
RUN apt-get update
# install cli from linux tarball with bundled node
RUN curl -s $DOWNLOAD_URL --output sf-linux-x64.tar.xz \
  && mkdir -p /usr/local/sf \
  && tar xJf sf-linux-x64.tar.xz -C /usr/local/sf --strip-components 1 \
  && rm sf-linux-x64.tar.xz

RUN apt-get install --assume-yes \
  openjdk-11-jdk-headless

RUN apt-get autoremove --assume-yes \
  && apt-get clean --assume-yes \
  && rm -rf /var/lib/apt/lists/*

ENV PATH="/usr/local/sf/bin:$PATH"
ENV SF_CONTAINER_MODE true
ENV DEBIAN_FRONTEND=dialog
ENV SHELL /bin/bash
