name: announce-RC
on:
  release:
    types: [published]
jobs:
  Post-RC-to-Slack:
    runs-on: ubuntu-latest
    steps:
      - name: Announce RC Workflow
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RC_ANNOUNCEMENT_WORKFLOW_WEBHOOK }}
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "cli": "sf",
              "npm-package": "@salesforce/cli",
              "version": "${{ github.event.release.tag_name }}"
            }
