name: jf-exp.yml
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
    

jobs:
  experiment-with-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: yarn
      - run: npm install --global @salesforce/cli
      - run: sf install sfdx-git-delta
