name: manual promote
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: numerical npm version to promote, like 7.166.2 (no tags!)
      channel:
        type: string
        required: true
        default: stable
        description: channel to promote the matching tarball to (example stable, stable-rc )
      tag:
        type: string
        required: false
        description: tag to use for docker/npm, like latest or latest-rc
        default: latest
      useCTC:
        type: boolean
        required: false
        default: false
        description: this promotion should only run if no release moratorium is in place

jobs:
  manual-promote:
    uses: ./.github/workflows/promote.yml
    secrets: inherit
    with:
      version: ${{inputs.version}}
      tag: ${{inputs.tag}}
      channel: ${{inputs.channel}}
      useCTC: ${{inputs.useCTC}}
